[project]
name = "protothrive-backend"
version = "0.1.0"
description = "Backend tooling for ProtoThrive"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.27.2"
]

[project.optional-dependencies]
dev = [
    "pytest==8.4.2",
    "pytest-asyncio==0.24.0"
]