[tool.poetry]
name = "ai-core"
version = "1.0.0"
description = "AI Core & Agent Orchestration for ProtoThrive"
authors = ["ProtoThrive Team <team@protothrive.com>"]
readme = "README.md"
python = "^3.12"

[tool.poetry.dependencies]
python = "^3.12"
langchain = "^0.1.0"
crewai = "^0.1.0"
pinecone-client = "^2.2.0"
python-dotenv = "^1.0.0"
numpy = "^1.24.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pylint = "^3.0.0"
pytest-cov = "^4.1.0"
black = "^23.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.messages_control]
max-line-length = 120
disable = ["C0111", "R0903", "W0613"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
addopts = "-v --cov=src --cov-report=term-missing"

[tool.black]
line-length = 120
target-version = ['py312']