# Ref: CLAUDE.md Terminal 1 Phase 1 - Workers Configuration
# Thermonuclear Cloudflare Workers Configuration for ProtoThrive

name = "backend-thermo"
main = "src/index.ts"
compatibility_date = "2024-08-23"
compatibility_flags = ["nodejs_compat"]

# Account and route configuration
account_id = "${CF_ACCOUNT_ID}"
workers_dev = true

# Environment variables
[vars]
ENVIRONMENT = "development"
SERVICE_NAME = "protothrive-backend"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "protothrive_thermo"
database_id = "${D1_ID}"

# KV Namespace binding
[[kv_namespaces]]
binding = "KV"
id = "${KV_ID}"
preview_id = "${KV_ID}"

# Build configuration
[build]
command = "npm run build"

# Development environment
[env.development]
name = "backend-thermo-dev"
vars = { ENVIRONMENT = "development" }

# Staging environment
[env.staging]
name = "backend-thermo-staging"
vars = { ENVIRONMENT = "staging" }

# Production environment
[env.production]
name = "backend-thermo-prod"
vars = { ENVIRONMENT = "production" }
route = "api.protothrive.com/*"

# Limits and usage model
[limits]
cpu_ms = 50

[usage_model]
default = "bundled"