name = "protothrive-backend-python"
main = "src/main.py"
compatibility_date = "2024-08-26"
compatibility_flags = ["python_workers"]

# Account and route configuration
account_id = "d2897bdebfa128919bd89b265e6a712e" # Placeholder, replace with actual
workers_dev = true

# Environment variables
[vars]
ENVIRONMENT = "development"
SERVICE_NAME = "protothrive-backend-python"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "protothrive-db"
database_id = "0b6970f4-c6ca-4245-aabf-98fa2d4f28a8" # Placeholder, replace with actual

# KV Namespace binding
[[kv_namespaces]]
binding = "KV"
id = "ec3183e7b4e94442b3f99b4d2f4b083e" # Placeholder, replace with actual
preview_id = "ec3183e7b4e94442b3f99b4d2f4b083e" # Placeholder, replace with actual

# Build configuration for Python Worker
[build]
command = "pip install -r requirements.txt" # Or poetry install if using poetry
python_requirements_file = "requirements.txt" # Or poetry.lock if using poetry

# Development environment
[env.development]
name = "protothrive-backend-python-dev"
vars = { ENVIRONMENT = "development" }

# Staging environment
[env.staging]
name = "protothrive-backend-python-staging"
vars = { ENVIRONMENT = "staging" }

# Production environment
[env.production]
name = "protothrive-backend-python-prod"
vars = { ENVIRONMENT = "production" }
route = "api.protothrive.com/*" # Placeholder, replace with actual
