version: "3.9"
services:
  worker:
    image: ghcr.io/cloudflare/workers-tools:latest
    command: ["wrangler", "dev", "--local"]
    working_dir: /workspace/backend
    volumes:
      - ../backend:/workspace/backend
    environment:
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}

  enterprise-agent:
    build:
      context: ../enterprise-agent
      dockerfile: Dockerfile
    volumes:
      - ../enterprise-agent:/app
    environment:
      - AGENT_ENV=local
    command: ["python", "agent_cli.py", "--serve"]

  d1-proxy:
    image: ghcr.io/cloudflare/d1-miniflare:latest
    ports:
      - "8788:8788"
    environment:
      - D1_DATABASE_NAME=protothrive_dev

networks:
  protothrive:
    driver: bridge
