input {
  beats {
    port => 5044
  }
}

filter {
  if [fields][service] == "frontend" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
  }
  
  if [fields][service] == "backend" {
    json {
      source => "message"
    }
  }
  
  if [fields][service] == "nginx" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
  }
  
  date {
    match => [ "timestamp", "ISO8601" ]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "protothrive-logs-%{+YYYY.MM.dd}"
  }
}
