// Ref: CLAUDE.md - Agent Coordination Layer
// Migrated from Python agent_coordinator.py to TypeScript
import { z } from 'zod';

export interface AgentResult {
  success: boolean;
  output: Record<string, any>;
  confidence: number;
  costEstimate: number;
  costActual: number;
  validation: Record<string, any>;
  agent: string;
  raw?: Record<string, any>;
  error?: string;
}

export interface CoordinatorOutcome {
  result: AgentResult;
  trace: AgentResult[];
  mode: string;
  budgetConsumed: number;
  budgetRemaining: number;
  fallbackUsed: boolean;
}

export interface AgentRequest {
  task: string;
  context: Record<string, any>;
}

export class AgentExecutionError extends Error {
  code: string;
  status: number;
  metadata: Record<string, any>;

  constructor(message: string, code: string = 'AGENT-500', status: number = 500, metadata: Record<string, any> = {}) {
    super(message);
    this.name = 'AgentExecutionError';
    this.code = code;
    this.status = status;
    this.metadata = metadata;
  }
}

abstract class AgentAdapter {
  name: string = 'base';
  defaultCostEstimate: number = 0.05;
  env: Record<string, any>;

  constructor(env: Record<string, any>) {
    this.env = env;
  }

  estimateCost(request: AgentRequest): number {
    return this.defaultCostEstimate;
  }

  abstract run(request: AgentRequest, remainingBudget: number, metadata: Record<string, any>): Promise<AgentResult>;
}

class EnterpriseAgentAdapter extends AgentAdapter {
  name = 'enterprise';
  defaultCostEstimate = 0.12;

  async run(request: AgentRequest, remainingBudget: number, metadata: Record<string, any>): Promise<AgentResult> {
    const endpoint = this.env.ENTERPRISE_AGENT_URL;

    if (!endpoint) {
      throw new AgentExecutionError('ENTERPRISE_AGENT_URL not configured', 'ENT-404', 501);
    }

    const headers = {
      'Content-Type': 'application/json',
      ...(this.env.ENTERPRISE_AGENT_TOKEN && {
        'Authorization': `Bearer ${this.env.ENTERPRISE_AGENT_TOKEN}`
      })
    };

    const payload = {
      task: request.task,
      context: request.context,
      budget: remainingBudget,
      mode: metadata.mode
    };

    try {
      // Mock implementation for now - would call actual Enterprise Agent API
      console.log('Thermonuclear: Executing Enterprise Agent', payload);

      // Simulate API response
      const mockResponse = {
        success: true,
        output: {
          code: `// Generated by Enterprise Agent\n// Task: ${request.task}\n// Budget: $${remainingBudget.toFixed(2)}`,
          analysis: 'Comprehensive analysis completed'
        },
        confidence: 0.87,
        cost_summary: {
          estimate: 0.10,
          actual: 0.09,
          total_cost: 0.09
        },
        validation: {
          passes: true,
          score: 0.95
        }
      };

      return {
        success: mockResponse.success,
        output: mockResponse.output,
        confidence: mockResponse.confidence,
        costEstimate: mockResponse.cost_summary.estimate,
        costActual: mockResponse.cost_summary.actual,
        validation: mockResponse.validation,
        agent: this.name,
        raw: mockResponse,
        error: undefined
      };
    } catch (error) {
      throw new AgentExecutionError(
        'Failed to execute Enterprise Agent',
        'ENT-500',
        500,
        { detail: error instanceof Error ? error.message : 'Unknown error' }
      );
    }
  }
}

class LightweightAgentAdapter extends AgentAdapter {
  name = 'lightweight';
  defaultCostEstimate = 0.02;

  async run(request: AgentRequest, remainingBudget: number, metadata: Record<string, any>): Promise<AgentResult> {
    try {
      // Mock lightweight agent execution
      console.log('Thermonuclear: Executing Lightweight Agent');

      const jsonGraph = typeof request.context.json_graph === 'string'
        ? request.context.json_graph
        : JSON.stringify(request.context.graph || { nodes: [], edges: [] });

      // Simulate lightweight processing
      const outputs = [
        `// Lightweight Agent Output\n// Processed: ${jsonGraph.length} characters`,
        `// Task: ${request.task}`,
        `// Mode: ${metadata.mode || 'default'}`
      ];

      const success = outputs.length > 0;
      const confidence = success ? 0.55 : 0.2;

      return {
        success,
        output: { generated: outputs },
        confidence,
        costEstimate: this.defaultCostEstimate,
        costActual: this.defaultCostEstimate,
        validation: {},
        agent: this.name,
        raw: { outputs },
        error: success ? undefined : 'No output generated'
      };
    } catch (error) {
      throw new AgentExecutionError(
        'Lightweight agent execution failed',
        'LITE-500',
        500,
        { detail: error instanceof Error ? error.message : 'Unknown error' }
      );
    }
  }
}

export class AgentCoordinator {
  private env: Record<string, any>;
  private mode: string;
  private defaultBudget: number;
  private maxBudget: number;
  private fallbackMinBudget: number;
  private confidenceThreshold: number;
  private primaryAdapter: EnterpriseAgentAdapter;
  private secondaryAdapter: LightweightAgentAdapter;

  constructor(env: Record<string, any>) {
    this.env = env;
    this.mode = (env.AGENT_MODE || 'single').toLowerCase();
    this.defaultBudget = parseFloat(env.AGENT_BUDGET_DEFAULT || '0.40');
    this.maxBudget = parseFloat(env.AGENT_BUDGET_MAX || '1.00');
    this.fallbackMinBudget = parseFloat(env.AGENT_BUDGET_FALLBACK_MIN || '0.05');
    this.confidenceThreshold = parseFloat(env.AGENT_CONFIDENCE_THRESHOLD || '0.8');

    this.primaryAdapter = new EnterpriseAgentAdapter(env);
    this.secondaryAdapter = new LightweightAgentAdapter(env);
  }

  async runTask(
    task: string,
    context: Record<string, any> = {},
    budget?: number,
    modeOverride?: string,
    metadata: Record<string, any> = {}
  ): Promise<CoordinatorOutcome> {
    if (!task) {
      throw new AgentExecutionError('Task prompt is required', 'REQ-400', 400);
    }

    const mode = (modeOverride || this.mode || 'single').toLowerCase();
    let remainingBudget = Math.min(this.maxBudget, budget || this.defaultBudget);

    if (remainingBudget <= 0) {
      throw new AgentExecutionError('Budget exhausted', 'COST-402', 402);
    }

    const request: AgentRequest = { task, context };
    const trace: AgentResult[] = [];
    let budgetConsumed = 0.0;

    // Execute primary adapter
    const [primaryResult, budgetAfterPrimary] = await this.attemptAdapter(
      this.primaryAdapter,
      request,
      remainingBudget,
      metadata
    );

    trace.push(primaryResult);
    budgetConsumed += primaryResult.costActual;
    remainingBudget = budgetAfterPrimary;

    // Determine if secondary should be used
    let useSecondary = false;
    if (mode === 'fallback') {
      useSecondary = !primaryResult.success || primaryResult.confidence < this.confidenceThreshold;
    } else if (mode === 'ensemble') {
      useSecondary = true;
    }

    // Execute secondary if needed
    if (useSecondary && remainingBudget >= this.fallbackMinBudget) {
      try {
        const [secondaryResult, budgetAfterSecondary] = await this.attemptAdapter(
          this.secondaryAdapter,
          request,
          remainingBudget,
          metadata,
          true // skipOnError
        );

        if (secondaryResult) {
          trace.push(secondaryResult);
          budgetConsumed += secondaryResult.costActual;
          remainingBudget = budgetAfterSecondary;
        }
      } catch (error) {
        console.warn('Secondary adapter failed, continuing with primary result', error);
      }
    }

    // Select best result
    const chosen = this.selectResult(trace, mode);
    const fallbackUsed = trace.some(r => r.agent !== chosen.agent && r.success);

    if (!chosen.success) {
      throw new AgentExecutionError(
        'No agent produced a successful result',
        'AGENT-417',
        502,
        { trace: trace.map(r => this.resultMetadata(r)) }
      );
    }

    return {
      result: chosen,
      trace,
      mode,
      budgetConsumed,
      budgetRemaining: remainingBudget,
      fallbackUsed
    };
  }

  private async attemptAdapter(
    adapter: AgentAdapter,
    request: AgentRequest,
    remainingBudget: number,
    metadata: Record<string, any>,
    skipOnError: boolean = false
  ): Promise<[AgentResult, number]> {
    const estimatedCost = adapter.estimateCost(request);

    if (estimatedCost > remainingBudget) {
      throw new AgentExecutionError(
        `Insufficient budget for ${adapter.name} (estimate ${estimatedCost.toFixed(2)})`,
        'COST-401',
        402,
        {
          adapter: adapter.name,
          estimate: estimatedCost,
          remaining_budget: remainingBudget
        }
      );
    }

    try {
      const result = await adapter.run(request, remainingBudget, metadata);
      const costUsed = Math.max(result.costActual, estimatedCost);
      const newBudget = Math.max(0.0, remainingBudget - costUsed);
      return [result, newBudget];
    } catch (error) {
      if (error instanceof AgentExecutionError) {
        if (!skipOnError) throw error;
      }

      if (skipOnError) {
        console.log(`Agent ${adapter.name} failed: ${error}`);
        const dummyResult: AgentResult = {
          success: false,
          output: {},
          confidence: 0.0,
          costEstimate: estimatedCost,
          costActual: 0.0,
          validation: {},
          agent: adapter.name,
          raw: { error: error instanceof Error ? error.message : 'Unknown error' },
          error: error instanceof Error ? error.message : 'Unknown error'
        };
        return [dummyResult, remainingBudget];
      }

      throw new AgentExecutionError(
        `Agent ${adapter.name} execution error`,
        'AGENT-500',
        500,
        {
          adapter: adapter.name,
          detail: error instanceof Error ? error.message : 'Unknown error'
        }
      );
    }
  }

  private selectResult(results: AgentResult[], mode: string): AgentResult {
    const successes = results.filter(r => r.success);

    if (successes.length === 0) {
      // Return highest confidence failure
      return results.reduce((best, current) =>
        current.confidence > best.confidence ? current : best
      );
    }

    // Prefer highest confidence; use cost as tiebreaker
    return successes.reduce((best, current) => {
      if (current.confidence > best.confidence) return current;
      if (current.confidence === best.confidence && current.costActual < best.costActual) return current;
      return best;
    });
  }

  private resultMetadata(result: AgentResult): Record<string, any> {
    return {
      agent: result.agent,
      confidence: result.confidence,
      cost_actual: result.costActual,
      success: result.success,
      error: result.error
    };
  }
}

// Helper function to determine status from error code
export function getStatusFromCode(code?: string): number {
  if (!code) return 500;
  if (code.startsWith('AUTH-')) return 401;
  if (code.startsWith('VAL-')) return 400;
  if (code.startsWith('GRAPH-')) return 404;
  if (code.startsWith('COST-')) return 402;
  if (code.startsWith('HTTP-')) {
    try {
      return parseInt(code.split('-')[1], 10);
    } catch {
      return 500;
    }
  }
  return 500;
}