/**
 * Comprehensive Accessibility Testing Suite
 * WCAG AA/AAA compliance validation and assistive technology testing
 * Generated by QA Engineer - 2025-01-03
 */

import { test, expect, Page } from '@playwright/test';

test.describe('Comprehensive Accessibility Testing', () => {
  
  test.describe('WCAG AA Compliance', () => {
    test('should meet color contrast requirements (4.5:1 ratio)', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Test primary text contrast
      const textElements = await page.locator('p, span, div, h1, h2, h3, h4, h5, h6').all();
      
      for (const element of textElements.slice(0, 20)) { // Test first 20 elements
        const styles = await element.evaluate((el) => {
          const computed = window.getComputedStyle(el);
          const rect = el.getBoundingClientRect();
          
          // Only test visible elements with text content
          if (rect.width === 0 || rect.height === 0 || !el.textContent?.trim()) {
            return null;
          }
          
          return {
            color: computed.color,
            backgroundColor: computed.backgroundColor,
            fontSize: computed.fontSize,
            textContent: el.textContent?.trim().substring(0, 50)
          };
        });
        
        if (styles && styles.textContent) {
          // Note: In production, use a proper color contrast calculator
          expect(styles.color).not.toBe('rgba(0, 0, 0, 0)'); // Not transparent
          expect(styles.color).not.toBe('transparent');
        }
      }
    });

    test('should have proper heading hierarchy', async ({ page }) => {
      await page.goto('/dashboard');
      
      const headings = await page.locator('h1, h2, h3, h4, h5, h6').all();
      let previousLevel = 0;
      
      for (const heading of headings) {
        const tagName = await heading.evaluate(el => el.tagName);
        const currentLevel = parseInt(tagName.charAt(1));
        
        // Heading levels should not skip (e.g., h1 -> h3)
        if (previousLevel > 0) {
          expect(currentLevel).toBeLessThanOrEqual(previousLevel + 1);
        }
        
        // First heading should be h1
        if (previousLevel === 0) {
          expect(currentLevel).toBe(1);
        }
        
        previousLevel = currentLevel;
      }
    });

    test('should have proper ARIA labels and roles', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Test interactive elements have accessible names
      const interactiveElements = await page.locator('button, [role="button"], input, select, textarea, a[href]').all();
      
      for (const element of interactiveElements) {
        const accessibility = await element.evaluate((el) => {
          return {
            ariaLabel: el.getAttribute('aria-label'),
            ariaLabelledBy: el.getAttribute('aria-labelledby'),
            ariaDescribedBy: el.getAttribute('aria-describedby'),
            textContent: el.textContent?.trim(),
            tagName: el.tagName,
            type: el.getAttribute('type'),
            alt: el.getAttribute('alt'),
            title: el.getAttribute('title')
          };
        });
        
        // Interactive elements should have accessible names
        const hasAccessibleName = !!(
          accessibility.ariaLabel ||
          accessibility.ariaLabelledBy ||
          accessibility.textContent ||
          accessibility.alt ||
          accessibility.title ||
          (accessibility.tagName === 'INPUT' && accessibility.type === 'submit')
        );
        
        expect(hasAccessibleName).toBe(true);
      }
    });

    test('should have proper form labels', async ({ page }) => {
      await page.goto('/login');
      
      const formInputs = await page.locator('input, select, textarea').all();
      
      for (const input of formInputs) {
        const labelInfo = await input.evaluate((el) => {
          const id = el.id;
          const label = id ? document.querySelector(`label[for="${id}"]`) : null;
          const ariaLabel = el.getAttribute('aria-label');
          const ariaLabelledBy = el.getAttribute('aria-labelledby');
          const placeholder = el.getAttribute('placeholder');
          
          return {
            hasLabel: !!label,
            hasAriaLabel: !!ariaLabel,
            hasAriaLabelledBy: !!ariaLabelledBy,
            hasPlaceholder: !!placeholder,
            labelText: label?.textContent?.trim(),
            type: el.getAttribute('type')
          };
        });
        
        // Form inputs should have proper labeling
        const isProperlyLabeled = 
          labelInfo.hasLabel || 
          labelInfo.hasAriaLabel || 
          labelInfo.hasAriaLabelledBy ||
          (labelInfo.type === 'submit' || labelInfo.type === 'button');
        
        expect(isProperlyLabeled).toBe(true);
      }
    });
  });

  test.describe('WCAG AAA Enhanced Features', () => {
    test('should support 400% zoom without horizontal scrolling', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Simulate 400% zoom
      await page.evaluate(() => {
        document.body.style.zoom = '4';
      });
      
      await page.waitForTimeout(1000);
      
      // Check for horizontal scrolling
      const scrollInfo = await page.evaluate(() => ({
        scrollWidth: document.body.scrollWidth,
        clientWidth: document.body.clientWidth,
        hasHorizontalScroll: document.body.scrollWidth > document.body.clientWidth
      }));
      
      // Content should reflow without horizontal scrolling
      expect(scrollInfo.hasHorizontalScroll).toBe(false);
      
      // Reset zoom
      await page.evaluate(() => {
        document.body.style.zoom = '1';
      });
    });

    test('should respect reduced motion preferences', async ({ page }) => {
      // Set reduced motion preference
      await page.emulateMedia({ reducedMotion: 'reduce' });
      await page.goto('/dashboard');
      
      // Trigger animation
      await page.click('[data-testid="mode-toggle"]');
      
      // Check that animations are reduced or disabled
      const animationDuration = await page.evaluate(() => {
        const computedStyle = window.getComputedStyle(document.documentElement);
        return computedStyle.getPropertyValue('--animation-duration') || 
               computedStyle.getPropertyValue('animation-duration');
      });
      
      // Animation should be reduced (0s or very short)
      expect(animationDuration === '0s' || animationDuration === '0.01s').toBe(true);
    });

    test('should maintain 7:1 contrast ratio for AAA compliance', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Test high contrast elements (this would need actual color calculation)
      const highContrastElements = await page.locator('.text-primary, .text-secondary, h1, h2, h3').all();
      
      for (const element of highContrastElements.slice(0, 10)) {
        const isVisible = await element.isVisible();
        if (isVisible) {
          const styles = await element.evaluate((el) => {
            const computed = window.getComputedStyle(el);
            return {
              color: computed.color,
              backgroundColor: computed.backgroundColor
            };
          });
          
          // In production, calculate actual contrast ratio
          expect(styles.color).toBeTruthy();
          expect(styles.backgroundColor).toBeTruthy();
        }
      }
    });
  });

  test.describe('Screen Reader Compatibility', () => {
    test('should announce dynamic content changes', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Check for ARIA live regions
      const liveRegions = await page.locator('[aria-live]').all();
      expect(liveRegions.length).toBeGreaterThan(0);
      
      // Test live region announcements
      for (const region of liveRegions) {
        const ariaLive = await region.getAttribute('aria-live');
        expect(['polite', 'assertive', 'off']).toContain(ariaLive);
      }
      
      // Trigger dynamic content change
      await page.evaluate(() => {
        const liveRegion = document.querySelector('[aria-live="polite"]');
        if (liveRegion) {
          liveRegion.textContent = 'Test announcement for screen readers';
        }
      });
      
      await page.waitForTimeout(1000);
      
      // Verify announcement text is present
      const announcement = await page.locator('[aria-live="polite"]').textContent();
      expect(announcement).toContain('Test announcement');
    });

    test('should have proper landmark navigation', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Check for landmark roles
      const landmarks = await page.locator('[role="main"], [role="navigation"], [role="banner"], [role="contentinfo"], [role="complementary"], main, nav, header, footer').all();
      
      expect(landmarks.length).toBeGreaterThan(0);
      
      // Verify main landmark exists
      const mainLandmarks = await page.locator('[role="main"], main').count();
      expect(mainLandmarks).toBeGreaterThanOrEqual(1);
      
      // Verify navigation landmarks
      const navLandmarks = await page.locator('[role="navigation"], nav').count();
      expect(navLandmarks).toBeGreaterThanOrEqual(1);
    });

    test('should provide skip links for navigation', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Focus first element and look for skip link
      await page.keyboard.press('Tab');
      
      const firstFocusedElement = await page.evaluate(() => {
        const el = document.activeElement;
        return el ? {
          textContent: el.textContent?.trim(),
          href: el.getAttribute('href'),
          className: el.className
        } : null;
      });
      
      // First focusable element should ideally be a skip link
      if (firstFocusedElement?.textContent) {
        const isSkipLink = firstFocusedElement.textContent.toLowerCase().includes('skip') ||
                          firstFocusedElement.href?.includes('#main') ||
                          firstFocusedElement.className.includes('skip');
        
        // If not a skip link, ensure main content is easily accessible
        if (!isSkipLink) {
          const mainContent = await page.locator('main, [role="main"]').first();
          expect(await mainContent.isVisible()).toBe(true);
        }
      }
    });
  });

  test.describe('Keyboard Navigation', () => {
    test('should support full keyboard operation', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Test Tab navigation
      const tabSequence = [];
      let previousElement = null;
      
      for (let i = 0; i < 15; i++) {
        await page.keyboard.press('Tab');
        
        const currentElement = await page.evaluate(() => {
          const el = document.activeElement;
          return el ? {
            tagName: el.tagName,
            type: el.getAttribute('type'),
            role: el.getAttribute('role'),
            ariaLabel: el.getAttribute('aria-label'),
            textContent: el.textContent?.trim().substring(0, 30)
          } : null;
        });
        
        if (currentElement && currentElement !== previousElement) {
          tabSequence.push(currentElement);
          previousElement = currentElement;
        }
      }
      
      // Should have a logical tab sequence
      expect(tabSequence.length).toBeGreaterThan(5);
      
      // Test Shift+Tab (reverse navigation)
      await page.keyboard.press('Shift+Tab');
      const reversedElement = await page.evaluate(() => {
        const el = document.activeElement;
        return el?.textContent?.trim().substring(0, 30);
      });
      
      // Should move backwards in sequence
      expect(reversedElement).toBeTruthy();
    });

    test('should handle modal focus trapping', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Try to open a modal (adjust selector based on your app)
      const modalTrigger = page.locator('[data-testid="open-modal"], button:has-text("Settings"), button:has-text("Help")').first();
      
      if (await modalTrigger.count() > 0) {
        await modalTrigger.click();
        
        // Wait for modal to open
        await page.waitForTimeout(500);
        
        // Check if modal traps focus
        const initialFocus = await page.evaluate(() => document.activeElement?.tagName);
        
        // Tab through modal elements
        for (let i = 0; i < 10; i++) {
          await page.keyboard.press('Tab');
        }
        
        // Focus should remain within modal
        const modalElements = await page.locator('[role="dialog"], .modal, [aria-modal="true"]').count();
        if (modalElements > 0) {
          const focusWithinModal = await page.evaluate(() => {
            const modal = document.querySelector('[role="dialog"], .modal, [aria-modal="true"]');
            const activeElement = document.activeElement;
            return modal && modal.contains(activeElement);
          });
          
          expect(focusWithinModal).toBe(true);
        }
      }
    });

    test('should support custom keyboard shortcuts', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Test global shortcuts (adjust based on your app)
      const shortcuts = [
        { key: 'Alt+N', action: 'new roadmap' },
        { key: 'Alt+S', action: 'save' },
        { key: 'Escape', action: 'close modal' },
        { key: '/', action: 'search' }
      ];
      
      for (const shortcut of shortcuts) {
        const beforeState = await page.evaluate(() => ({
          activeElement: document.activeElement?.tagName,
          url: window.location.href
        }));
        
        await page.keyboard.press(shortcut.key);
        await page.waitForTimeout(300);
        
        const afterState = await page.evaluate(() => ({
          activeElement: document.activeElement?.tagName,
          url: window.location.href
        }));
        
        // Some change should occur (focus change, URL change, modal open, etc.)
        const stateChanged = 
          beforeState.activeElement !== afterState.activeElement ||
          beforeState.url !== afterState.url;
        
        // Note: This test would need to be more specific based on actual shortcuts
        if (shortcut.key === 'Escape') {
          // Escape should generally close modals or return to safe state
          expect(stateChanged || true).toBe(true); // Placeholder assertion
        }
      }
    });
  });

  test.describe('Voice Control and Assistive Technology', () => {
    test('should have descriptive accessible names for voice commands', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Elements that should be voice-controllable
      const voiceTargets = await page.locator('button, [role="button"], input, select').all();
      
      for (const element of voiceTargets) {
        const accessibleName = await element.evaluate((el) => {
          // Calculate accessible name (simplified version)
          return el.getAttribute('aria-label') ||
                 el.getAttribute('aria-labelledby') ||
                 el.textContent?.trim() ||
                 el.getAttribute('alt') ||
                 el.getAttribute('title') ||
                 el.getAttribute('placeholder');
        });
        
        if (accessibleName) {
          // Accessible names should be descriptive enough for voice commands
          expect(accessibleName.length).toBeGreaterThan(2);
          expect(accessibleName).not.toMatch(/^(click|button|link)$/i); // Avoid generic names
        }
      }
    });

    test('should support high contrast modes', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Simulate high contrast mode
      await page.emulateMedia({ colorScheme: 'dark' });
      await page.evaluate(() => {
        document.documentElement.style.filter = 'contrast(2) brightness(1.5)';
      });
      
      await page.waitForTimeout(1000);
      
      // Verify content is still readable
      const textElements = await page.locator('h1, h2, h3, p, button, a').all();
      
      for (const element of textElements.slice(0, 10)) {
        const isVisible = await element.isVisible();
        if (isVisible) {
          const textContent = await element.textContent();
          expect(textContent?.trim().length).toBeGreaterThan(0);
        }
      }
      
      // Reset styles
      await page.evaluate(() => {
        document.documentElement.style.filter = '';
      });
    });
  });

  test.describe('Mobile Accessibility', () => {
    test('should have proper touch target sizes on mobile', async ({ page }) => {
      await page.setViewportSize({ width: 375, height: 667 });
      await page.goto('/dashboard');
      
      const touchTargets = await page.locator('button, [role="button"], a, input, select').all();
      
      for (const target of touchTargets) {
        const isVisible = await target.isVisible();
        if (isVisible) {
          const box = await target.boundingBox();
          if (box) {
            // WCAG guideline: minimum 44px for touch targets
            expect(Math.min(box.width, box.height)).toBeGreaterThanOrEqual(44);
          }
        }
      }
    });

    test('should support mobile screen reader gestures', async ({ page }) => {
      await page.setViewportSize({ width: 375, height: 667 });
      await page.goto('/dashboard');
      
      // Simulate screen reader navigation
      const headings = await page.locator('h1, h2, h3, h4, h5, h6').all();
      
      // Should be able to navigate by headings
      expect(headings.length).toBeGreaterThan(0);
      
      for (const heading of headings) {
        const headingText = await heading.textContent();
        expect(headingText?.trim().length).toBeGreaterThan(0);
      }
      
      // Test landmark navigation
      const landmarks = await page.locator('main, nav, header, footer, [role="main"], [role="navigation"]').all();
      expect(landmarks.length).toBeGreaterThan(0);
    });
  });
});