/**
 * Performance Stress Testing Suite
 * Max compute scenarios and performance budget validation
 * Generated by QA Engineer - 2025-01-03
 */

import { test, expect, Page } from '@playwright/test';

test.describe('Performance Stress Testing', () => {
  
  test.describe('Max Compute Scenarios', () => {
    test('should handle 1000+ concurrent user simulation', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Simulate high concurrency load
      await page.evaluate(() => {
        // Simulate multiple users making rapid changes
        const simulateUserActivity = () => {
          for (let i = 0; i < 100; i++) {
            setTimeout(() => {
              // Simulate user interactions
              const events = [
                new CustomEvent('user-action', { detail: { type: 'node-update', userId: `user-${i}` }}),
                new CustomEvent('user-action', { detail: { type: 'canvas-zoom', userId: `user-${i}` }}),
                new CustomEvent('user-action', { detail: { type: 'notification', userId: `user-${i}` }})
              ];
              
              events.forEach(event => window.dispatchEvent(event));
            }, i * 10); // Rapid fire events
          }
        };
        
        // Run simulation multiple times
        for (let round = 0; round < 10; round++) {
          setTimeout(simulateUserActivity, round * 1000);
        }
      });
      
      // Wait for load simulation
      await page.waitForTimeout(12000);
      
      // Test UI responsiveness under load
      const startTime = Date.now();
      await page.click('[data-testid="mode-toggle"]');
      const responseTime = Date.now() - startTime;
      
      expect(responseTime).toBeLessThan(1000); // Should respond within 1 second under load
      
      // Check memory usage
      const memoryInfo = await page.evaluate(() => {
        if ('memory' in performance) {
          return {
            usedJSHeapSize: (performance as any).memory.usedJSHeapSize,
            totalJSHeapSize: (performance as any).memory.totalJSHeapSize,
            jsHeapSizeLimit: (performance as any).memory.jsHeapSizeLimit
          };
        }
        return null;
      });
      
      if (memoryInfo) {
        // Memory should not exceed 100MB under stress
        expect(memoryInfo.usedJSHeapSize).toBeLessThan(100 * 1024 * 1024);
      }
    });

    test('should maintain performance on slow 3G network', async ({ page }) => {
      // Throttle network to simulate slow 3G
      const client = await page.context().newCDPSession(page);
      await client.send('Network.enable');
      await client.send('Network.emulateNetworkConditions', {
        offline: false,
        downloadThroughput: 500 * 1024, // 500 KB/s
        uploadThroughput: 500 * 1024,   // 500 KB/s
        latency: 500 // 500ms latency
      });
      
      const startTime = Date.now();
      await page.goto('/dashboard');
      const loadTime = Date.now() - startTime;
      
      // Should load within reasonable time even on slow network
      expect(loadTime).toBeLessThan(10000); // 10 seconds max on slow 3G
      
      // Test interaction responsiveness
      const interactionStart = Date.now();
      await page.click('[data-testid="new-roadmap"]', { timeout: 15000 });
      const interactionTime = Date.now() - interactionStart;
      
      expect(interactionTime).toBeLessThan(3000); // Interactions should be responsive
      
      // Disable network throttling
      await client.send('Network.emulateNetworkConditions', {
        offline: false,
        downloadThroughput: -1,
        uploadThroughput: -1,
        latency: 0
      });
    });

    test('should handle memory-constrained devices', async ({ page }) => {
      // Simulate memory pressure
      await page.evaluate(() => {
        // Create memory pressure by allocating large arrays
        const memoryHogs: any[] = [];
        for (let i = 0; i < 50; i++) {
          memoryHogs.push(new Array(100000).fill(`memory-pressure-${i}`));
        }
        
        // Store in global scope to prevent garbage collection
        (window as any).memoryPressure = memoryHogs;
      });
      
      await page.goto('/dashboard');
      
      // Create complex roadmap under memory pressure
      await page.fill('[data-testid="vision-input"]', 'Complex enterprise application with multiple microservices, APIs, databases, and user interfaces');
      await page.click('[data-testid="generate-roadmap"]');
      
      // Wait for generation
      await page.waitForTimeout(5000);
      
      // Test canvas performance under memory pressure
      const canvas = page.locator('[data-testid="magic-canvas"]');
      await expect(canvas).toBeVisible({ timeout: 10000 });
      
      // Test zoom and pan under memory constraints
      const zoomStart = Date.now();
      await canvas.wheel(0, 0, { deltaY: -500 });
      const zoomTime = Date.now() - zoomStart;
      
      expect(zoomTime).toBeLessThan(1000); // Should remain responsive
      
      // Clean up memory pressure
      await page.evaluate(() => {
        delete (window as any).memoryPressure;
      });
    });

    test('should handle high CPU usage scenarios', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Simulate high CPU usage
      await page.evaluate(() => {
        const startCPUIntensiveTask = () => {
          // CPU-intensive calculation
          const worker = setInterval(() => {
            let result = 0;
            for (let i = 0; i < 1000000; i++) {
              result += Math.random() * Math.sin(i) * Math.cos(i);
            }
            console.log('CPU intensive task result:', result);
          }, 100);
          
          // Store reference to clean up later
          (window as any).cpuWorker = worker;
          
          return worker;
        };
        
        startCPUIntensiveTask();
      });
      
      // Test UI responsiveness during CPU stress
      await page.waitForTimeout(2000); // Let CPU stress run
      
      const interactionTimes = [];
      
      // Test multiple interactions
      for (let i = 0; i < 5; i++) {
        const start = Date.now();
        await page.click('[data-testid="mode-toggle"]');
        await page.waitForTimeout(100);
        const end = Date.now();
        interactionTimes.push(end - start);
      }
      
      // Average interaction time should be reasonable
      const avgTime = interactionTimes.reduce((a, b) => a + b, 0) / interactionTimes.length;
      expect(avgTime).toBeLessThan(2000); // 2 seconds max under CPU stress
      
      // Clean up CPU worker
      await page.evaluate(() => {
        if ((window as any).cpuWorker) {
          clearInterval((window as any).cpuWorker);
          delete (window as any).cpuWorker;
        }
      });
    });
  });

  test.describe('Large Dataset Performance', () => {
    test('should handle 1000+ node roadmaps efficiently', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Generate large dataset
      const largeRoadmap = await page.evaluate(() => {
        const nodes = [];
        const edges = [];
        
        // Create 1000 nodes
        for (let i = 0; i < 1000; i++) {
          nodes.push({
            id: `node-${i}`,
            label: `Task ${i}: Implement feature module ${Math.floor(i / 10)}`,
            position: {
              x: (i % 50) * 150,
              y: Math.floor(i / 50) * 100,
              z: Math.floor(i / 250) * 50
            },
            status: i % 3 === 0 ? 'completed' : i % 3 === 1 ? 'in-progress' : 'pending',
            priority: i % 4 === 0 ? 'high' : i % 4 === 1 ? 'medium' : 'low'
          });
          
          // Create connections
          if (i > 0) {
            edges.push({
              from: `node-${i - 1}`,
              to: `node-${i}`
            });
          }
          
          // Add some random connections for complexity
          if (i > 10 && Math.random() > 0.8) {
            edges.push({
              from: `node-${Math.floor(Math.random() * (i - 10))}`,
              to: `node-${i}`
            });
          }
        }
        
        return { nodes, edges };
      });
      
      // Load large dataset
      const loadStart = Date.now();
      await page.evaluate((roadmap) => {
        window.dispatchEvent(new CustomEvent('load-large-roadmap', {
          detail: roadmap
        }));
      }, largeRoadmap);
      
      // Wait for initial render
      await page.waitForTimeout(3000);
      const loadTime = Date.now() - loadStart;
      
      expect(loadTime).toBeLessThan(5000); // Should load within 5 seconds
      
      // Test canvas operations with large dataset
      const canvas = page.locator('[data-testid="magic-canvas"]');
      
      // Test zoom performance
      const zoomStart = Date.now();
      await canvas.wheel(0, 0, { deltaY: -1000 }); // Deep zoom
      await page.waitForTimeout(500);
      const zoomTime = Date.now() - zoomStart;
      
      expect(zoomTime).toBeLessThan(1000); // Zoom should be smooth
      
      // Test pan performance
      const panStart = Date.now();
      await page.mouse.move(100, 100);
      await page.mouse.down();
      await page.mouse.move(300, 300);
      await page.mouse.up();
      await page.waitForTimeout(500);
      const panTime = Date.now() - panStart;
      
      expect(panTime).toBeLessThan(1000); // Pan should be smooth
      
      // Test search in large dataset
      const searchStart = Date.now();
      await page.fill('[data-testid="search-nodes"]', 'Task 500');
      await page.waitForTimeout(1000);
      const searchTime = Date.now() - searchStart;
      
      expect(searchTime).toBeLessThan(2000); // Search should be fast
    });

    test('should virtualize large lists for performance', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Generate large notification list
      await page.evaluate(() => {
        for (let i = 0; i < 500; i++) {
          window.dispatchEvent(new CustomEvent('test-notification', {
            detail: {
              id: `notif-${i}`,
              message: `Test notification ${i} with some longer content to test rendering performance`,
              type: i % 4 === 0 ? 'critical' : i % 4 === 1 ? 'warning' : i % 4 === 2 ? 'info' : 'success',
              timestamp: new Date(Date.now() - i * 1000)
            }
          }));
        }
      });
      
      // Wait for notifications to load
      await page.waitForTimeout(2000);
      
      // Test scroll performance
      const notificationPanel = page.locator('[data-testid="notification-panel"]');
      
      if (await notificationPanel.count() > 0) {
        const scrollStart = Date.now();
        
        // Rapid scrolling test
        for (let i = 0; i < 10; i++) {
          await notificationPanel.wheel(0, 0, { deltaY: 500 });
          await page.waitForTimeout(50);
        }
        
        const scrollTime = Date.now() - scrollStart;
        expect(scrollTime).toBeLessThan(2000); // Smooth scrolling
        
        // Check if virtualization is working (not all items rendered)
        const renderedItems = await page.locator('[data-testid="notification-item"]').count();
        expect(renderedItems).toBeLessThan(500); // Should virtualize, not render all 500
      }
    });
  });

  test.describe('Animation Performance', () => {
    test('should maintain 60fps during complex animations', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Start performance monitoring
      await page.evaluate(() => {
        (window as any).frameRates = [];
        (window as any).lastFrameTime = performance.now();
        
        const measureFrameRate = () => {
          const currentTime = performance.now();
          const deltaTime = currentTime - (window as any).lastFrameTime;
          const fps = 1000 / deltaTime;
          (window as any).frameRates.push(fps);
          (window as any).lastFrameTime = currentTime;
          
          if ((window as any).frameRates.length < 120) { // Monitor for 2 seconds at 60fps
            requestAnimationFrame(measureFrameRate);
          }
        };
        
        requestAnimationFrame(measureFrameRate);
      });
      
      // Trigger complex animations
      await page.click('[data-testid="mode-toggle"]'); // 3D transition
      await page.waitForTimeout(1000);
      
      // Trigger multiple notifications with animations
      await page.evaluate(() => {
        for (let i = 0; i < 20; i++) {
          setTimeout(() => {
            window.dispatchEvent(new CustomEvent('test-notification', {
              detail: {
                message: `Animated notification ${i}`,
                type: 'info'
              }
            }));
          }, i * 100);
        }
      });
      
      await page.waitForTimeout(3000);
      
      // Analyze frame rates
      const frameRateStats = await page.evaluate(() => {
        const rates = (window as any).frameRates || [];
        if (rates.length === 0) return null;
        
        const avgFps = rates.reduce((a: number, b: number) => a + b, 0) / rates.length;
        const minFps = Math.min(...rates);
        const framesBelow60 = rates.filter((fps: number) => fps < 60).length;
        const percentBelow60 = (framesBelow60 / rates.length) * 100;
        
        return {
          avgFps,
          minFps,
          percentBelow60,
          totalFrames: rates.length
        };
      });
      
      if (frameRateStats) {
        expect(frameRateStats.avgFps).toBeGreaterThan(55); // Average should be close to 60fps
        expect(frameRateStats.percentBelow60).toBeLessThan(20); // Less than 20% frames below 60fps
      }
    });

    test('should handle reduced motion preferences', async ({ page }) => {
      // Enable reduced motion
      await page.emulateMedia({ reducedMotion: 'reduce' });
      await page.goto('/dashboard');
      
      // Test that animations are reduced
      const animationDuration = await page.evaluate(() => {
        // Check CSS custom properties for animation duration
        const style = getComputedStyle(document.documentElement);
        return {
          transitionDuration: style.getPropertyValue('--transition-duration'),
          animationDuration: style.getPropertyValue('--animation-duration')
        };
      });
      
      // Animations should be reduced or disabled
      expect(
        animationDuration.transitionDuration === '0s' ||
        animationDuration.transitionDuration === '0.01s' ||
        animationDuration.animationDuration === '0s' ||
        animationDuration.animationDuration === '0.01s'
      ).toBe(true);
      
      // Test that functionality still works without animations
      await page.click('[data-testid="mode-toggle"]');
      await page.waitForTimeout(500);
      
      // Mode should still change, just without animation
      const modeChanged = await page.evaluate(() => {
        return document.querySelector('[data-testid="magic-canvas"]')?.getAttribute('data-mode') !== null;
      });
      
      expect(modeChanged).toBe(true);
    });
  });

  test.describe('Bundle Size and Loading Performance', () => {
    test('should meet performance budgets', async ({ page }) => {
      // Navigate and measure resource loading
      await page.goto('/dashboard');
      
      // Wait for full page load
      await page.waitForLoadState('networkidle');
      
      // Analyze bundle sizes and loading performance
      const performanceMetrics = await page.evaluate(() => {
        const navigation = performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming;
        const resources = performance.getEntriesByType('resource') as PerformanceResourceTiming[];
        
        // Calculate bundle sizes
        const jsResources = resources.filter(r => r.name.includes('.js'));
        const cssResources = resources.filter(r => r.name.includes('.css'));
        
        const totalJSSize = jsResources.reduce((total, resource) => {
          return total + (resource.transferSize || 0);
        }, 0);
        
        const totalCSSSize = cssResources.reduce((total, resource) => {
          return total + (resource.transferSize || 0);
        }, 0);
        
        return {
          // Loading performance
          domContentLoaded: navigation.domContentLoadedEventEnd - navigation.domContentLoadedEventStart,
          loadComplete: navigation.loadEventEnd - navigation.loadEventStart,
          firstContentfulPaint: performance.getEntriesByName('first-contentful-paint')[0]?.startTime || 0,
          timeToInteractive: navigation.domInteractive - navigation.navigationStart,
          
          // Bundle sizes (approximate)
          totalJSSize: totalJSSize,
          totalCSSSize: totalCSSSize,
          totalAssetSize: totalJSSize + totalCSSSize,
          
          // Resource counts
          resourceCount: resources.length,
          jsResourceCount: jsResources.length,
          cssResourceCount: cssResources.length
        };
      });
      
      // Performance budget assertions
      expect(performanceMetrics.timeToInteractive).toBeLessThan(4000); // 4 seconds TTI
      expect(performanceMetrics.totalAssetSize).toBeLessThan(1.5 * 1024 * 1024); // 1.5MB total
      expect(performanceMetrics.resourceCount).toBeLessThan(50); // Reasonable resource count
      
      console.log('Performance Metrics:', performanceMetrics);
    });

    test('should code split effectively for large applications', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Initial bundle should be small
      const initialResources = await page.evaluate(() => {
        return performance.getEntriesByType('resource').length;
      });
      
      // Navigate to different sections to trigger code splitting
      const sections = [
        '[data-testid="settings-tab"]',
        '[data-testid="analytics-tab"]',
        '[data-testid="admin-tab"]'
      ];
      
      for (const section of sections) {
        const element = page.locator(section);
        if (await element.count() > 0) {
          await element.click();
          await page.waitForTimeout(1000);
        }
      }
      
      // Should have loaded additional chunks
      const finalResources = await page.evaluate(() => {
        return performance.getEntriesByType('resource').length;
      });
      
      // New resources should have been loaded (code splitting working)
      expect(finalResources).toBeGreaterThan(initialResources);
      
      // But total size should still be reasonable
      const totalSize = await page.evaluate(() => {
        const resources = performance.getEntriesByType('resource') as PerformanceResourceTiming[];
        return resources.reduce((total, resource) => {
          return total + (resource.transferSize || 0);
        }, 0);
      });
      
      expect(totalSize).toBeLessThan(2 * 1024 * 1024); // 2MB max total
    });
  });

  test.describe('Real-time Performance', () => {
    test('should handle WebSocket updates efficiently', async ({ page }) => {
      await page.goto('/dashboard');
      
      // Simulate rapid WebSocket updates
      await page.evaluate(() => {
        let updateCount = 0;
        const startTime = performance.now();
        
        const simulateWebSocketUpdates = () => {
          const update = {
            type: 'roadmap-update',
            nodeId: `node-${Math.floor(Math.random() * 100)}`,
            change: {
              status: Math.random() > 0.5 ? 'completed' : 'in-progress',
              timestamp: Date.now()
            }
          };
          
          window.dispatchEvent(new CustomEvent('websocket-update', {
            detail: update
          }));
          
          updateCount++;
          
          if (updateCount < 200) { // 200 rapid updates
            setTimeout(simulateWebSocketUpdates, 50); // Every 50ms
          } else {
            const endTime = performance.now();
            (window as any).wsUpdatePerformance = {
              totalUpdates: updateCount,
              totalTime: endTime - startTime,
              avgUpdateTime: (endTime - startTime) / updateCount
            };
          }
        };
        
        simulateWebSocketUpdates();
      });
      
      // Wait for updates to complete
      await page.waitForTimeout(12000);
      
      // Check update performance
      const wsPerformance = await page.evaluate(() => {
        return (window as any).wsUpdatePerformance;
      });
      
      if (wsPerformance) {
        expect(wsPerformance.avgUpdateTime).toBeLessThan(5); // Under 5ms per update
        expect(wsPerformance.totalUpdates).toBe(200);
      }
      
      // UI should remain responsive
      const uiResponseTime = await page.evaluate(async () => {
        const start = performance.now();
        
        // Trigger UI interaction
        const button = document.querySelector('[data-testid="mode-toggle"]') as HTMLElement;
        if (button) {
          button.click();
        }
        
        // Wait for next frame
        await new Promise(resolve => requestAnimationFrame(resolve));
        
        return performance.now() - start;
      });
      
      expect(uiResponseTime).toBeLessThan(100); // UI should respond quickly
    });
  });
});