# Ref: CLAUDE.md - Cloudflare Pages Configuration
name = "protothrive-frontend"
compatibility_date = "2024-08-23"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.mjs"]
fallthrough = true